const IMAGES = {
  logoYellow: new URL('./logo-yellow.png', import.meta.url).href,
  logoBlue: new URL('./logo-blue.png', import.meta.url).href,
  person1: new URL('./person.png', import.meta.url).href,
  person2: new URL('./person1.png', import.meta.url).href,
  person3: new URL('./person2.png', import.meta.url).href,
  person3: new URL('./person2.png', import.meta.url).href,
  brand1: new URL('./brand1.png', import.meta.url).href,
  brand2: new URL('./brand2.png', import.meta.url).href,
  brand3: new URL('./brand3.png', import.meta.url).href,
  brand4: new URL('./brand4.png', import.meta.url).href,
  brand5: new URL('./brand5.png', import.meta.url).href,
  brand6: new URL('./brand6.png', import.meta.url).href,
  brand7: new URL('./brand7.png', import.meta.url).href,
  brand8: new URL('./brand8.png', import.meta.url).href,
  team1: new URL('./teamwork.jpg', import.meta.url).href,
  team2: new URL('./teamwork1.jpg', import.meta.url).href,
  team3: new URL('./teamwork2.jpg', import.meta.url).href,
  option1: new URL('./option1.png', import.meta.url).href,
  option2: new URL('./option2.png', import.meta.url).href,
  option3: new URL('./option3.png', import.meta.url).href,
  option4: new URL('./option4.png', import.meta.url).href,
  personOption: new URL('./person_option.png', import.meta.url).href,
  back_header1: new URL('./background_header.png', import.meta.url).href,
  back_header2: new URL('./back_header1.png', import.meta.url).href,
}

export default IMAGES
